/*SUBQUERIES - SUBCONJUNTO DO CONJUNTO*/

SELECT * FROM VENDEREDORES;

/*SELECIONAR O VENDEDOR QUE VENDEU MENOS EM MARCO E SEU NOME*/
SELECT MIN(MARCO)
FROM VENDEREDORES;

SELECT NOME, MARCO
FROM VENDEREDORES
WHERE MARCO = (SELECT MIN(MARCO) FROM VENDEREDORES);
--INNER QUERIE SERA EXECUTADO PRIMEIRO

/*NOME E O VALOR QUE VENDEU MAIS EM MARCO*/

SELECT NOME, MARCO
FROM VENDEREDORES
WHERE MARCO = (SELECT MAX(MARCO) FROM VENDEREDORES);

/*QUEM VENDEU MAIS QUE O VALOR MEDIO EM FEV*/

SELECT NOME, FEVEREIRO
FROM VENDEREDORES
WHERE FEVEREIRO > (SELECT AVG(FEVEREIRO) FROM VENDEREDORES);

SELECT NOME, FEVEREIRO
FROM VENDEREDORES
WHERE FEVEREIRO < (SELECT AVG(FEVEREIRO) FROM VENDEREDORES);

/*OPERACOES EM LINHA*/

SELECT NOME, 
	   JANEIRO,
	   FEVEREIRO,
	   MARCO,
	   (JANEIRO+FEVEREIRO+MARCO) AS 'TOTAL',
	   TRUNCATE((JANEIRO+FEVEREIRO+MARCO)/3,2) AS 'MEDIA'
FROM VENDEREDORES;

/*APLICANDO UM %*/

SELECT NOME, 
	   JANEIRO,
	   FEVEREIRO,
	   MARCO,
	   (JANEIRO+FEVEREIRO+MARCO) AS 'TOTAL',
	   (JANEIRO+FEVEREIRO+MARCO)* 0.25 AS 'DESCONTO',
	   TRUNCATE((JANEIRO+FEVEREIRO+MARCO)/3,2) AS 'MEDIA'
FROM VENDEREDORES;