/* ENTENDENDO UMA TRIGGER(GATILHO)*/

/* ESTRUTURA DE UMA TRIGGER*/

CREATE TRIGGER NOME
BEFORE/AFTER INSERT/DELETE/UPDATE ON TABELA
FOR EACH ROW (PARA CADA LINHA)
BEGIN -> INICIO
	QUALQUER COMANDO SQL;
END -> FIM
$

/* LEMBRAR DE USAR O DELIMITADOR */
