/*Auto Relacionamento*/


CREATE TABLE CURSOS(
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	HORAS INT,
	VALOR FLOAT(10,2),
	ID_PREREQ INT
);

ALTER TABLE CURSOS ADD CONSTRAINT FK_PREREQ
FOREIGN KEY (ID_PREREQ) REFERENCES CURSOS(IDCURSO);

CREATE DATABASE AULA44;

USE AULA44;
/* NESSE CASO DEVEMOS CRIAS OS CURSOS DEPOIS FAZER ADICIONAR OS REQUISITOS
	NO PRIMEIRO MOMENTO ID_PREREQ DEVE SER NULL ;
*/

INSERT INTO CURSOS VALUES (NULL,'BD RELACIONAL',20,400.00,NULL);
INSERT INTO CURSOS VALUES (NULL,'BD RELACIONAL 2',22,402.00,4);
INSERT INTO CURSOS VALUES (NULL,'BD RELACIONAL 3',23,403.00,7));

SELECT * FROM CURSOS;

/*EXERCICIO NOME DO PRE-REQUISITO*/
--TESTE 1 ERRADO
SELECT C.NOME , C.VALOR , C.HORAS , IFNULL(CP.NOME,"SEM REQ") REQUISITO
FROM CURSOS C
INNER JOIN CURSOS CP ON(C.IDCURSO = CP.ID_PREREQ)
;

---CORRETO
SELECT C.NOME , C.VALOR , C.HORAS , IFNULL(CP.NOME,"SEM REQ") REQUISITO
FROM CURSOS C
LEFT JOIN CURSOS CP ON(C.ID_PREREQ = CP.IDCURSO)
;

--CORRECAO PROFESSOR

SELECT 
C.NOME AS CURSO,
C.VALOR AS VALOR,
C.HORAS AS CARGA,
IFNULL(P.NOME,'---') AS PREREQ
FROM CURSOS C
LEFT JOIN CURSOS P
ON P.IDCURSO = C.ID_PREREQ;