/*ATIVIDADE 3*/

/*RELATORIO GERAL DE TODOS OS CLIENTES (TELEFONE E ENDERECO)*/

SELECT IDCLIENTE, NOME, SEXO, EMAIL, CPF, RUA, BAIRRO, CIDADE, ESTADO,TIPO
,NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T 
ON C.IDCLIENTE = T.ID_CLIENTE;

/*TRAZER OS HOMEM*/

SELECT IDCLIENTE, NOME, SEXO, EMAIL, CPF, RUA, BAIRRO, CIDADE, ESTADO,TIPO
,NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T 
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'M';

/*TRAZER AS MULHERES*/
SELECT IDCLIENTE, NOME, SEXO, EMAIL, CPF, RUA, BAIRRO, CIDADE, ESTADO,TIPO
,NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T 
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'F';

/*QUANTIDADE DE HOMENS E MULHERES*/

SELECT COUNT(*) AS QUANTIDADE, SEXO
FROM CLIENTE
GROUP BY SEXO;

/*ID E EMAIL DAS MULHERES QUE MOREM NO CENTRO DO RIO DE JANIERO E NAO TENHA CELULAR*/

SELECT C.IDCLIENTE , C.EMAIL, C.NOME, C.SEXO, T.TIPO
FROM CLIENTE C
INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T 
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE C.SEXO = 'F' 
AND E.BAIRRO = 'CENTRO'
AND E.CIDADE = 'RIO DE JANEIRO';

/* PARA UMA COMPANHA DE MARKENTING, O SETOR SOLICITOU UM 
RELATORIO COM O NOME, EMAIL E TELEFONE CELUALR DOS CLIENTES QUE MORAM NO
ESTADO DO RIO DE JANEIRO VOCE TERA QUE PASSAR A QUERY PARA GERAR O RELATORIO
PARA O PROGRAMADOR*/

SELECT C.NOME,C.EMAIL, T.NUMERO AS CELULAR
FROM CLIENTE C
INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T 
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE T.TIPO = 'CEL' 
AND E.ESTADO = 'RJ';



/*PARA UMA CAMPANHA DE PRODUTOS DE BELEZA, O COMERCIAL SOLICITOU UM RELATORIO
COM O NOME, EMAIL E TELEFONE CELULAR DAS MULHERES QUE MORAM NO ESTADO DE SÃO PAULO
VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA O PROGRAMADOR*/

SELECT C.NOME,C.EMAIL, T.NUMERO AS CELULAR
FROM CLIENTE C
INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T 
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE C.SEXO = 'F' 
AND E.ESTADO = 'SP';
