/*FUNCOES DE AGREGACAO*/

CREATE TABLE VENDEREDORES(
	IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	SEXO CHAR(1),
	JANEIRO FLOAT(10,2),
	FEVEREIRO FLOAT(10,2),
	MARCO FLOAT(10,2)
);

INSERT INTO VENDEREDORES VALUES (NULL,'CARLOS','M',788.22,342.33,2323.93);
INSERT INTO VENDEREDORES VALUES (NULL,'JESSICA','F',78.00,342.00,230.93);
INSERT INTO VENDEREDORES VALUES (NULL,'FABIANO','M',769.00,3427.00,2133.93);

--TRAZ VALOR MAXIMO DE UMA COLUNA
SELECT MAX(FEVEREIRO) AS MAIRO_FEV
FROM VENDEREDORES;

--TRAZ VALOR MINIMO DE UMA COLUNA
SELECT MIN(FEVEREIRO) AS MENOR_FEV
FROM VENDEREDORES;

--AVG - TRAZ O VALOR MEDIO
SELECT AVG(FEVEREIRO) AS MEDIA_FEV
FROM VENDEREDORES;

---USANDO VARIAS

SELECT MAX(JANEIRO) AS MAIOR_JAN,
	   MIN(JANEIRO) AS MENOR_JAN,
	   AVG(JANEIRO) AS MEDIA_JAN
FROM VENDEREDORES;

---FUNCAO TRUNCATE ESSA FUNCAO PEDE DOIS PARAMETRO
---TRUNCATE(1 NUMERO, 2 QUANTIDADE DE PARAMETRO);
SELECT MAX(JANEIRO) AS MAIOR_JAN,
	   MIN(JANEIRO) AS MENOR_JAN,
	   TRUNCATE(AVG(JANEIRO),2) AS MEDIA_JAN
FROM VENDEREDORES;

---AGREGANDO COM SUM()

SELECT SUM(JANEIRO) AS TOTAL_JAN,
	   SUM(FEVEREIRO) AS TOTAL_FEV,
       SUM(MARCO) AS TOTAL_MAR
FROM VENDEREDORES;

---VENDAS POR SEXO
SELECT SEXO , SUM(MARCO) AS TOTAL_MARCO
FROM VENDEREDORES
GROUP BY SEXO;


--O BANCO DE DADOS E USADO PARA 
--PEGAR DADOS E GERAR E INFORMACAO

