/* Modelagem 
DEVEMOS MODELAR NOSSO BANCO VOLTADO A DADOS, 
E NAO A REGRAS DE NEGOCIO;*/
/*
PRIMEIRA FORMA NORMAL

1 - Todo campo vetorizado(mesma familia) se tornara outra tabela

[amarelo,azul,laranja,verde] - vetor cores
[ka, fiesta, uno , civic] - vetor carros

2- Todo campo multivalorado se tornara outra tabela.
quando o campo for divisivel

COLUNA - ENDERECO
LINHA - RUA FULANO DE TAL , 123, BAIRRO TAL, CIDADE TAL , UF TAL

3 - TODA TABLE NECESSITA DE PELO MENOS UM CAMPO QUE IDENTIFIQUE TODO O 
REGISTRO COMO SENDO UNICO.
ISSO E O QUE CHAMAMOS DE CHAVE PRIMARIA OU PRIMARY KEY.


*/

/*CARDINALIDADE E OBRIGATORIEDADE

quem define tua cardinalidade e tua regra de negocio

1-OBRIGATORIEDADE ( 0 = falso/nao obrigatorio e 1 = verdadeiro/obrigatorio)(minimo que vai acontecer)

2- CARDINALIDADE (maximo que vai acontecer)

(0,n)
(0,1)
(1,n)
(1,1)
 EX: 
 Endereco - obrigatorio o cadastro de um endereco
 R= (1,1)
 Telefone - o cliente nao e obrigado a informar telefone
 porem, caso queira, ele pode informar mais de um.
 
r= (0,n)


*OBS: a leitura e de acordo com o segundo numero de cada par*
*/

CREATE DATABASE COMERCIO;
 
USE COMERCIO;

SHOW DATABES;

/*CHAVE PRIMARIA E O IDENTIFICADOR DA TABELA*/

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(11) UNIQUE
);
--ENUM SO TEM NO MYSQL
SHOW TABLES;

CREATE TABLE ENDERRECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES','COM','CEL') NOT NULL,--SO TEM NO MYSQL
	NUMERO VARCHAR(10) NOT NULL
);

/* CHAVE ESTRANGEIRA E A CHAVE PRIMARIA DE UMA TABELA
QUE VAI ATE A OUTRA TABELA PRA FAZER REFERENCIA
ENTRE REGISTROS*/

/* 
EM RELACIONAMENTO 1x1 A CHAVE ESTRANGEIRA FICA NA TABELA MAIS FRACA

EM RELACIONAMENTO 1xN A CHAVE ESTRANGEIRA FICA SEMPRE NA CARDINALIDADE N
*/

DROP TABLE CLIENTE;

/*
Criar Constraint
*/
CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY (ID_CLIENTE) 
	REFERENCES CLIENTE(IDCLIENTE) 
);
--ID_CLIENTE tem que ser do mesmo tipo da id refenciada
-- O relacionamento e 1x1 entao deve ter um unique

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES','COM','CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT,
	FOREIGN KEY (ID_CLIENTE) 
	REFERENCES CLIENTE(IDCLIENTE)
);
--ID_CLIENTE tem que ser do mesmo tipo da id refenciada

--VERIFICAR O QUE TEM DENTRO DA TABELA TIPO DE DADOS E ETC...

DESC CLIENTE;

INSERT INTO CLIENTE VALUES(null,'JOAO','M','','123456789');
INSERT INTO CLIENTE VALUES(null,'CARLOS','M','c@C.com','123424888');
INSERT INTO CLIENTE VALUES(null,'JORGE','M',NULL,'123456713');
INSERT INTO CLIENTE VALUES(null,'CELIA','F','cel@cel.com','123451275');
INSERT INTO CLIENTE VALUES(null,'ANA','F','a@a.com','12345235');

/*INSERCAO 1x1 */

DESC CLIENTE;
/*integridade referencial o banco sempre verificar se a referencia existe*/
desc ENDERECO
INSERT INTO ENDERECO VALUES(NULL,'RUA ANTONIO','CENTRO','BELO','MG',1);
INSERT INTO ENDERECO VALUES(NULL,'RUA FULANO DE TAL','HAUER','CURITIBA','PR',2);
INSERT INTO ENDERECO VALUES(NULL,'RUA RIO','PORTAO','CURITIBA','PR',3);
INSERT INTO ENDERECO VALUES(NULL,'RUA CICLANO','CABRAL','CURITIBA','PR',4);
INSERT INTO ENDERECO VALUES(NULL,'RUA PAULO','CENTRO','CURITIBA','PR',5);

/*INSERCAO 1xN */

DESC TELEFONE;
--NULL SO NO MYSQL;
INSERT INTO TELEFONE VALUES(NULL,'CEL','123456778',5);
INSERT INTO TELEFONE VALUES(NULL,'RES','546456343',5);
INSERT INTO TELEFONE VALUES(NULL,'CEL','434312215',1);
INSERT INTO TELEFONE VALUES(NULL,'COM','123468999',2);
INSERT INTO TELEFONE VALUES(NULL,'RES','111222333',1);
INSERT INTO TELEFONE VALUES(NULL,'CEL','555111222',3);
INSERT INTO TELEFONE VALUES(NULL,'CEL','777333222',3);
INSERT INTO TELEFONE VALUES(NULL,'COM','999955666',1);
INSERT INTO TELEFONE VALUES(NULL,'RES','999666644',5);
INSERT INTO TELEFONE VALUES(NULL,'CEL','211222333',2);