/* ORGANIZAR FISICAMENTE E LOGICAMENTE UM BANCO DE DADOS

1- CRIAR O BANCO COM ARQUIVOS PARA OS SETORES DE MKT E RH.
2- CRIAR UM ARQUIVO GERAL
3-DEIXAR O MDF APENAS COM O DICIONARIO DE DADOS
4- CRIAR 2 GRUPOS DE ARQUIVOS(PRIMARY - MDF)

*/


USE EMPRESA 
GO

CREATE TABLE TB_EMPRESA(
	ID INT,
	NOME VARCHAR(50)	
)
GO

CREATE TABLE ALUNO(
	IDALUNO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	EMAIL VARCHAR(30) UNIQUE
)
GO

--OBS ATIVIDADE REALIZADA NO BANCO SQL SERVER