/* ORGANIZAR FISICAMENTE E LOGICAMENTE UM BANCO DE DADOS

1- CRIAR O BANCO COM ARQUIVOS PARA OS SETORES DE MKT E RH.
2- CRIAR UM ARQUIVO GERAL
3-DEIXAR O MDF APENAS COM O DICIONARIO DE DADOS
4- CRIAR 2 GRUPOS DE ARQUIVOS(PRIMARY - MDF)

*/


USE EMPRESA 
GO

CREATE TABLE TB_EMPRESA(
	ID INT,
	NOME VARCHAR(50)	
)
GO

CREATE TABLE ALUNO(
	IDALUNO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	EMAIL VARCHAR(30) UNIQUE
)
GO

/* NAO CRIE CONSTRAINTS POR DENTRO DA TABELA POIS ELE NOMEIA
ALEATORIO*/

/* CONSTRAINTS*/

ALTER TABLE ALUNO
ADD CONSTRAINT CK_SEXO CHECK (SEXO IN ('M','F'))
GO

/* 1 - 1*/

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY IDENTITY(100,10),
	BAIRRO VARCHAR(30),
	UF CHAR(2) NOT NULL
	CHECK (UF IN('RJ','SP','MG')),
	ID_ALUNO INT UNIQUE
)
GO

/*CRIANDO A FK*/

ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_ALUNO
FOREIGN KEY(ID_ALUNO) REFERENCES ALUNO(IDALUNO)
GO

/* COMANDO DE DESCRICAO

 PROCEDURES JA CRIADAS E ARMAZENAS NO SISTEMA
 
*/

--MOSTRA DETALHES

SP_COLUMNS ALUNO
GO

--MOSTRA MAIS DETALHES
SP_HELP ALUNO 
GO

/* INSERINDO DADOS*/
INSERT INTO ALUNO VALUES('ANDRE','M','1994/12/22','ANDERE@A.COM')
INSERT INTO ALUNO VALUES('ANDRE2','M','1993/03/22','ANDERE2@A.COM')
INSERT INTO ALUNO VALUES('ANDRE3','M','1992/02/22','ANDERE3@A.COM')
INSERT INTO ALUNO VALUES('ANDRE4','M','1991/01/22','ANDERE4@A.COM')
GO